services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Model\CurrencyRateService:
    arguments:
      $exchangeRates: \App\Model\RateProvider

  App\Model\CountryDataProvider:
    arguments:
      $binCountryCode: \App\Model\BinLookupService

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Model\RateProvider:
    arguments:
      $accessToken: '%env(string:RATES_API_KEY)%'
      $apilayerUrl: '%env(string:APILAYER_URL)%'

  App\Model\BinLookupService:
    arguments:
      $binLookupUrl: '%env(string:BIN_LOOKUP_URL)%'
